GitHub workflow testing missing ref PR merge
```
  Error: fatal: couldn't find remote ref refs/pull/<PR_ID>/merge
  The process '/usr/bin/git' failed with exit code 128
```